language: java
jdk:
  - openjdk8

brances:
  only:
    - main   # main 브랜치에 push 가 되었을 때 Travis CI 반응

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"   # jar 만들기

before_deploy:
  - zip -r SpringBoot_Nginx *
  - mkdir -p deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - mv SpringBoot_Nginx.zip deploy/SpringBoot_Nginx.zip # deploy로 zip파일(원하는 이름으로) 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY         # Travis CI 에서 IAM 사용자 엑세스 키

    secret_access_key: $AWS_SECRET_KEY     # Travis CI 에서 IAM 사용자 비밀 엑세스 키

    bucket: hanghaefinal    # S3 Bucket 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private               # zip 파일 공개 여부
    local_dir: deploy
    wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY        # Travis CI 에서 IAM 사용자 엑세스 키

    secret_access_key: $AWS_SECRET_KEY    # Travis CI 에서 IAM 사용자 비밀 엑세스 키

    bucket: hanghaefinal         # S3 Bucket 이름
    key: SpringBoot_Nginx.zip   # 위에서 만든 zip 파일 이름 !! (꼭 맞춰서 적어야함)
    bundle_type: zip
    application: HfinalDeploy          # CodeDeploy 애플리케이션 이름

    deployment_group: HfinalDeploy   # CodeDeploy 배포 그룹 이름

    region: ap-northeast-2
    wait-until-deployed: true

notification:  # 이메일 알림
  email:
    recipients:
      - sjs939883@gmail.com