version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${{ secrets.MY_DB }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MY_PWD }}
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379