server:
  port: 80

---
spring:
  profiles:
    group:
      "real1": "real1_port"
---

spring:
  config:
    activate:
      on-profile: "real1_port"

server:
  port: 8081

---

spring:
  profiles:
    group:
      "real2": "real2_port"
---

spring:
  config:
    activate:
      on-profile: "real2_port"

server:
  port: 8082

---

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: $MYSQL_URL
    # DB username
    username: $MYSQL_USERNAME
    # DB password
    password: $MYSQL_PWD

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

cloud:
  aws:
    credentials:
      accessKey:
        $AWS_ACC
      secretKey:
        $AWSSEC
    s3:
      bucket:
        $S3
    region:
      static:
        $REGION
      stack:
        auto: false
