server:
  port: 80

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: ${{ secrets.RDS_HOST }}
    # DB username
    username: ${{ secrets.RDS_USERNAME }}
    # DB password
    password: ${{ secrets.RDS_PASSWORD }}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

cloud:
  aws:
    credentials:
      accessKey:
        ${aws.s3.accesskey}
      secretKey:
        ${aws.s3.secretkey}
    s3:
      bucket:
        ${aws.s3.bucketname}
    region:
      static:
        ${{ secrets.AWS_REGION }}
      stack:
        auto: false
